### ISSUE TITLE
Values put in manually override slider limitations

### ISSUE THREAD

**Issue by loicsander** [byte-foundry/prototypo#110]
Not sure it is an issue per se, it may be interesting but it does screw the visual appearance of the slider if you enter a value that goes beyond the slider’s limit.

![capture decran 2014-02-26 a 11 28 26](https://f.cloud.github.com/assets/5807259/2270260/cf96e4c4-9ee9-11e3-8964-da75e805a0b1.png)

**Comment by FranzPoize** [comment]
36a392b
