### ISSUE TITLE
Font export doesn't work in Safari

### ISSUE THREAD

**Issue by louisremi** [byte-foundry/prototypo#111]

**Comment by FranzPoize** [comment]
We don't support safari until

**Comment by Mouvedia** [comment]
Until…?

**Comment by FranzPoize** [comment]
Until safari support ```new FontFace(buffer)``` API https://developer.mozilla.org/en-US/docs/Web/API/CSS_Font_Loading_API

**Comment by davelab6** [comment]
Is Safari supported now?

**Comment by Mouvedia** [comment]
@davelab6 since September.
cf http://caniuse.com/#feat=font-loading

**Comment by Aldrian** [comment]
We have a few problems regarding the use of shared workers that are not supported by Safari, but we are working on a workaround. With that fixed, supporting this browser should be ok.
