### ISSUE TITLE
Collaborate with other libre font editor web app projects on common libraries

### ISSUE THREAD

**Issue by davelab6** [byte-foundry/prototypo#115]
Wow! Massive congratulations on the [kickstarter](https://www.kickstarter.com/projects/599698621/prototypo-streamlining-font-creation) - I'm sure you'll go way beyond your modest target! :)

There are a few other font tool web apps that I'd like to suggest collaborating with:

[Typism](http://typism.appspot.com) (by @xxyxyz) is a traditional outline font editor for SVG fonts. It exports SVG fonts to be compiled offline, the same as Prototypo.

[Glyphr Studio](http://glyphrstudio.com) (by @mattlag) is a traditional outline font editor for OpenType-CFF. It exports TTX xml to be compiled offline.

[Metapolator](http://metapolator.com) (by @simonegli and many others) is a parametric font editor that applies 'convention over configuration' to hijack metafont; it can do interpolation of masters made with outline editors (so-called 'superpolation') and it can derive new masters from 1+ existing ones, using 'off the peg' metafont programs ('metapolation'.) It is a reboot of the [Metaflop](http://metaflop.com) project, which has a client-side UI of slides that set parameters of true (hand-coded) metafonts, and a server-side system to run metapost on the metafont with the given parameters and return an OTF as a web font. The first prototype of metapolator reused this design. The new prototype is 100% client-side, using NodeBox's opentype.js for superpolation and a metapost.js (made with Emscripten) for metapolation.

[Font Bakery](https://github.com/googlefonts/fontbakery/) (maintained by @hash3g) and now is a continuous integration server and web interface for UFO and TTX format fonts stored in git. It clones a repo, locates font files to build, runs tests on UFO and TTX source fonts, compiles them with FontForge and fontTools (and [ttfautohint](http://freetype.org/ttfautohint)) and runs more tests on the font binaries. It provides a utilitarian UI to proven server-side font tools, and Bootstrap is more than enough. However, a fonts dashboard to [droni.io](http://drone.io) might be better, as that CI server has good momentum and would allow Font Bakery to focus on the things that make it unique.

[Impallari Testing Tool](http://www.impallari.com/testing/) by @impallari is a document-driven typeface test app, to test the _design_ of a type. By improving this and making the tests encapsulated, I hope it can be embedded in other tools - all those I just listed, and prototypo.

I think there is a lot of value in the fundamentally different approaches each project takes, and I do not propose merging them. Yet I see 3 clear common areas that all projects will benefit from, by pooling our limited resources on our common goals to maximize our impact :)
#### Git and Github repo reading and writing

Its great for studios of designers to store known-good versions of their projects in git, even if they aren't using for every little revision of every file. 

The Github REST API is powerful enough that it can serve as a 'file system' to web apps, and http://prose.io is a great example. 

Font Bakery already uses git to structure its input of UFO/TTX font files, and it would be great if all font editor web apps also had this option. 

Once a web app has access to a binary font file, of course, then its time for....
#### Client Side SFNT Reading

**[opentype.js](https://github.com/nodebox/opentype.js)** by Frederik @fdb De Bleser, is seeing active community contributions and core development thanks to Prototypo :) So this currently seems to be the leading candidate, and both prototypo and metapolator use this.

**[ttf.js](https://github.com/ynakajima/ttf.js)** At the Libre Graphics Meeting, I met in person with Denis @moyogo Jacquerye (of DejaVu fonts fame, now a software engineer at Dalton Maag) who is working on the development branch of ttf.js, which is very similar to opentype.js, written in coffeescript. It would be great to not duplicate this effort.

**[ufoJS](https://github.com/graphicore/ufoJS)** Also at LGM was Lasse @graphicore Fister, who worked on ufoJS a while ago, and will be much more active on this in the coming months as part of metapolator. Perhaps this code can partner with another.

**[binary-parser](https://github.com/Pomax/A-binary-parser-generator/)** Mike @Pomax Kamermans worked on this a while back, and many other fonts-in-browsers experimental utilities, and of course was involved in pdf.js. The spec file approach is neat, and follows Brandon @Benvie Benvie (also at Mozilla)'s approach from 2 years ago in [reified ttf example](https://github.com/Benvie/reified/tree/master/examples/ttf)

**[opentype](https://github.com/bramstein/opentype)** Bram @bramstein Stein works in Adobe Typekit and made this, which already (I think) has more OTL table support than ttf.js or opentype.js. Again, it would be great not to duplicate this effort. 

**[fontTools](https://github.com/behdad/fonttools/)** In theory, @behdad's fontTools could be transpiled to C and then transpiled to JS. This brings us to the next item...
#### Client Side SFNT Writing

Louis-Rémi emailed me a while back about funding opentype.js to add font binary generation, and I've since emailed a bit with Frederik about it. But neither thread reached a clear conclusion... 

I know Glyphr Studio, Prototypo and Metapolator would love to have this. The immediate option is to do it server-side, using fontTools or FontForge.

Glyphr offers TTX files as a download format, and requires users to run fontTool's ttx offline to build binary files. 

If we make a fontTools.js, then Glyphr could immediately provide binaries 100% client-side. 

All other font editor web apps would then merely need to export TTX files in the same way. 

It would also be possible to put FontForge through Emscripten, although a fontforge.js would be heavier than a fonttools.js. (The next stable release of fontforge is coming soon - June?)

Eventually @adobe will make the FDK libre, then we could also make a fdk.js

The nice thing about FontForge is that is has so many features. The pity is that its UI is from the 90s (or earlier :) Which leads me to...
#### Font Editor UI Toolkit

Both metapolator and prototypo use AngularJS as an MVC framework. Glyphr Studio uses its own. 

This month Alex @Troush has been shedding Metapolator's python parts and taking it full client, starting with a directive for an [opentype.js interpolator](metapolator.com/index_old.html) using paperjs and-or two.js for `<canvas>` rendering. He has also set up bower and gulp (instead of grunt) to structure the setup process.

Angular promises the possibility of making a 'font editor web app toolkit'.

I would like to suggest we share as much as possible.

**Comment by davelab6** [comment]
I thought I'd update this issue 

> opentype.js 

This has been actively developed by a vibrant developer community, and supports basic SFNT writing - which the prototypo team have combined with paperjs to produce www.pluminjs.com :)

> ufoJS 

This has been actively developed by its maintainer, and support UFOv3

> adobe will make the FDK libre

They did! https://github.com/adobe-type-tools/afdko

> I've looked at ufoJS, and it seems that we might be able to use it to produce ufo-structured JSON files.

In the short term, there is https://github.com/byte-foundry/unzip-ufo :)

Also something not captured on this thread is the need for OpenType Layout processing in JavaScript. The @prezi company have done something similar to what is described at the top, and ported Harfbuzz to JS with emscripten! 

See a prezi about this at https://prezi.com/zybglpjalpkl/conquering-multi-platform-text-rendering-wwx2013/ and video of the presentation at https://www.youtube.com/watch?v=yvQpt6hCzU8

**Comment by davelab6** [comment]
There's now also https://github.com/devongovett/fontkit

**Comment by davelab6** [comment]
@fdb I wonder if you could comment on what new support you think opentype.js will ship over the next 6 months. Everyone else, what area of OpenType standard do you think improvement is most needed in?

**Comment by mattlag** [comment]
@fdb @davelab6 at least for Glyphr Studio, it would be great to have:
1. Kern writing support (GPOS)
2. Table writing (font.tables.name, font.tables.os2, etc)
3. Ligature writing support (GSUB)

In that order :-)

**Comment by louisremi** [comment]
@fdb @davelab6 What @mattlag said : )
We are willing to sponsor some of that work, once our financial situation improves.

**Comment by fdb** [comment]
@davelab6 @mattlag @louisremi I have some time in July-August where I would love to have more robust support for font writing. I think it would be cool to have deep control over what gets written in the tables. With that as a foundation, you would already be able to use it for kerning and ligatures, although it would be pretty low-level.

On top of that would be more "user-facing" support for things like kerning and ligatures, like I have now with glyphs. That is: you provide the info, and OpenType.js makes sure everything gets written to the correct table(s).

I wouldn't mind at all for this work to be sponsored. I think the collaboration with @louisremi last year, where we agreed on a work package and compensation, worked out really well for everyone.

**Comment by davelab6** [comment]
Do you want to continue the discussion publicly or privately?

**Comment by fdb** [comment]
@davelab6 I don't mind discussion feature scope here, or as issues/milestones in opentype.js. Talk about sponsored development, I'd prefer we discuss privately (email is at https://github.com/fdb).

**Comment by fdb** [comment]
Okay I've added a ["Font Writhing"](https://github.com/nodebox/opentype.js/milestones/Font%20Writhing) milestone to OpenType.js that covers the issues mentioned by @mattlag. You're free to add comments / suggestions there.

**Comment by MartinDesigner** [comment]
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
So, as a supplement, however as a main point try this amazing free app. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. You can even design UI mockups for mobile as for standard display (html, js, css always generating without any coding required from you). Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi

**Comment by Pomax** [comment]
This issue is collecting quite a bit of dust in my github.com/issues/mentioned list because it's been open for 2 years since the last comment: is it possible to close this and capture the information in it on a repo wiki page instead?

**Comment by davelab6** [comment]
Sure, no need to capture it elsewhere for me. 

Since the last comment, a few summary thoughts:

* https://www.google.com/search?q=opentype+variable+fonts happened - which is really great :)

* @devongovett has done an amazing job with https://github.com/devongovett/fontkit (eg http://fontkit-demo.now.sh using it as a polyfill for variable fonts) and it seems to be leading the other js sfnt libraries discussed above

* prototypo has been continuously developed, although not as a typical libre software project

* metapolator went very far but not far enough to be really useful to end users as prototypo now is, although I expect @graphicore will continue to push it forwards 

* glyphr studio is undergoing a complete rewrite,
 which as a hobby project is fine per https://www.joelonsoftware.com/2000/04/06/things-you-should-never-do-part-i/ ;)

* @adientetar launched https://github.com/trufont/trufont which is a Python 3 font editor platform that uses many of the foundation libraries of RoboFont, but with PyQt instead of Apple's Cocoa library
