### ISSUE TITLE
After installation, http://0.0.0.0:9000 has opened... why?

### ISSUE THREAD

**Issue by iegik** [byte-foundry/prototypo#170]
On Windows, there are no such IP address 0.0.0.0. There is only 127.0.0.1 or localhost.
```
Running "connect:livereload" (connect) task
Started connect web server on http://0.0.0.0:9000

Running "watch" task
Waiting...
```
Btw. http://127.0.0.1:9000 - is working ok.

**Comment by louisremi** [comment]
This should be fixed when we switch from livereload to BrowserSync. We're gonne use bug #176 to track progress on this issue.
