### ISSUE TITLE
Replace the broken gruntfile with a working gulpfile

### ISSUE THREAD

**Issue by latsami** [byte-foundry/prototypo#175]
Hello,
I'm very curious about the project (have tried a bit MetaFont/Post) and tried to install it on Arch Linux.
I have the following error in the Console:
http://localhost:9000/genese.ptf/dist/font.json?typeface=default 404 (Not Found)

I can see the menus, I can type in the top left corner and in the main text area once I click on the "text block" icon. But I cannot see how to start a font. Clicking on "New font" doesn't do much.

Did I miss something in the install? 
Thanks for your help.

**Comment by yannickmathey** [comment]
Hello,
Which branch do you use? The latest (prototypo2) requires to make an alias from genese.ptf (branch john fell plumin) and prototypo.js in the prototypo directory.
The "New Font" button resets the current font to default settings.

**Comment by davelab6** [comment]
You could use git submodules to make this link

**Comment by latsami** [comment]
Hey, thanks for your help.
I cloned prototypo2 branch indeed. I cloned genese.ptf (john fell plumin branch), but I'm not sure in what directory I should put the alias. I'm not very familiar with Grunt.

**Comment by yannickmathey** [comment]
from genese directory: $ npm link
then in prototypo directory: $ npm link genese.ptf

**Comment by latsami** [comment]
I still have the same error in the Console. 
Here's my Terminal output when I relaunched the link commands:

    ➜  prototypo git:(prototypo2) ✗ cd ../genese.ptf        
    ➜  genese.ptf git:(john-fell-plumin) sudo npm link           
    npm WARN package.json karma-chrome-launcher@0.1.7 No README data
    npm WARN package.json karma-firefox-launcher@0.1.4 No README data
    npm WARN package.json karma-mocha@0.1.10 No README data
    npm WARN package.json karma-phantomjs-launcher@0.1.4 No README data
    /usr/lib/node_modules/Genese -> /home/svilayphiou/src/genese.ptf
    ➜  genese.ptf git:(john-fell-plumin) cd ../prototypo 
    ➜  prototypo git:(prototypo2) ✗ sudo npm link genese.ptf
    Genese@0.1.0 ../../../../usr/lib/node_modules/Genese
    unbuild Genese@0.1.0
    /home/svilayphiou/src/prototypo/node_modules/Genese -> ../../../../usr/lib/node_modules/Genese -> /usr/lib/node_modules/genese.ptf
    ➜  prototypo git:(prototypo2) ✗

**Comment by louisremi** [comment]
Can you pull from byte-foundry/genese.ptf#john-fell-plumin again and try the procedure Yannick indicated?
from genese directory: $ npm link
then in prototypo directory: $ npm link genese.ptf

**Comment by latsami** [comment]
Still doesn't find the file in the browser Console.
I reinstalled everything from new clones of both repos, just to be sure. (btw, maybe you can add the `bower install` command? Took me a while to figure it out.)
In node_modules, I do see a genese.ptf symlink.

**Comment by louisremi** [comment]
François Poizat is going to join the team in two weeks and will work on making the installation and build simpler (well, working, actually).

**Comment by louisremi** [comment]
We're gonna use bug #176 to track progress on this issue.
