### ISSUE TITLE
Rewrite the install+serve+build scripts

### ISSUE THREAD

**Issue by louisremi** [byte-foundry/prototypo#176]
We'll switch from our old and messy Gruntfile to a Gulpfile, ideally using gulp-shelter (see [prototypo.js' gulpfile](https://github.com/byte-foundry/prototypo.js/blob/master/gulpfile.js)). The objective is to make Prototypo installable with a single command and without any global dependency (except Node/npm and Git, (and Hoodie-server, but we'll ignore that problem for now)).

- [x] Remove all Bower dependencies, only use npm, even for client-side dependencies
- [x] Use BrowserSync instead of livereload
- [ ] Find a way to open the locally hosted Prototypo on a mobile device (does BrowserSync allows this?)
- [x] Deploy to [surge](http://surge.sh/) instead of AWS
- [x] Deployment should be automatically handled by Travis when commits are pushed to prototypo#master
- [ ] Parametric typefaces are in node_modules but should be sym-linked to from a typeface folder, and properly copied to that folder when deploying
- [x] it should be possible to include some scripts conditionally, only in specific environments (analytics, user-voice scripts, which slow down the app during debugging)

**Comment by FranzPoize** [comment]
there is still a bower file but just because I keep the old app for reference sake

**Comment by louisremi** [comment]
Okay, the new build system is perfectible but operational.
