### ISSUE TITLE
Problem with installing. Fatal error: Unable to find Gruntfile.

### ISSUE THREAD

**Issue by asffds2014** [byte-foundry/prototypo#179]
Hi!
Can't install your beautiful program.
Windows 8.1 - 64bit
What has been done:
- Git 1.9.5  - http://git-scm.com/download/win 
- Node.js (32/64 .msi try both) - https://nodejs.org/download/

- Grunt
installing grunt (run Command-line as Administrator):
Microsoft Windows [Version 6.3.9600]
C:\Windows\system32>npm install -g grunt-cli
C:\Users\000\AppData\Roaming\npm\grunt -> C:\Users\000\AppData\Roaming\n
pm\node_modules\grunt-cli\bin\grunt
grunt-cli@0.1.13 C:\Users\000\AppData\Roaming\npm\node_modules\grunt-cli
├── resolve@0.3.1
├── nopt@1.0.10 (abbrev@1.0.7)
└── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)
C:\Windows\system32>grunt --version
grunt-cli v0.1.13

- Bower
Microsoft Windows [Version 6.3.9600]
C:\Windows\system32>npm install -g bower
C:\Users\000\AppData\Roaming\npm\bower -> C:\Users\000\AppData\Roaming\n
pm\node_modules\bower\bin\bower
bower@1.4.1 C:\Users\000\AppData\Roaming\npm\node_modules\bower
├── is-root@1.0.0
├── junk@1.0.2
├── stringify-object@1.0.1
├── chmodr@0.1.0
├── user-home@1.1.1
├── abbrev@1.0.7
├── rimraf@2.4.1
├── archy@1.0.0
├── bower-logger@0.2.2
├── graceful-fs@3.0.8
├── bower-endpoint-parser@0.2.2
├── lockfile@1.0.1
├── opn@1.0.2
├── lru-cache@2.6.5
├── retry@0.6.1
├── nopt@3.0.3
├── tmp@0.0.24
├── q@1.4.1
├── request-progress@0.3.1 (throttleit@0.0.2)
├── semver@2.3.2
├── shell-quote@1.4.3 (array-filter@0.0.1, array-reduce@0.0.0, array-map@0.0.0,
jsonify@0.0.0)
├── bower-json@0.4.0 (intersect@0.0.3, deep-extend@0.2.11, graceful-fs@2.0.3)
├── fstream@1.0.7 (inherits@2.0.1)
├── p-throttler@0.1.1 (q@0.9.7)
├── which@1.1.1 (is-absolute@0.1.7)
├── promptly@0.2.0 (read@1.0.6)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2
.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── fstream-ignore@1.0.2 (inherits@2.0.1, minimatch@2.0.8)
├── glob@4.5.3 (inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@2.0.8)
├── tar-fs@1.7.0 (pump@1.0.0, tar-stream@1.2.1)
├── insight@0.5.3 (object-assign@2.1.1, lodash.debounce@3.1.1, async@0.9.2, os-n
ame@1.0.3, tough-cookie@0.12.1)
├── decompress-zip@0.1.0 (mkpath@0.1.0, touch@0.0.3, readable-stream@1.1.13, bin
ary@0.3.0)
├── update-notifier@0.3.2 (is-npm@1.0.0, string-length@1.0.1, semver-diff@2.0.0,
 latest-version@1.0.1)
├── bower-registry-client@0.3.0 (graceful-fs@2.0.3, request-replay@0.2.0, rimraf
@2.2.8, lru-cache@2.3.1, mkdirp@0.3.5, async@0.2.10, request@2.51.0)
├── github@0.2.4 (mime@1.3.4)
├── request@2.53.0 (caseless@0.9.0, aws-sign2@0.5.0, forever-agent@0.5.2, string
stream@0.0.4, tunnel-agent@0.4.1, oauth-sign@0.6.0, isstream@0.1.2, json-stringi
fy-safe@5.0.1, qs@2.3.3, node-uuid@1.4.3, combined-stream@0.0.7, form-data@0.2.0
, mime-types@2.0.14, bl@0.9.4, http-signature@0.10.1, tough-cookie@2.0.0, hawk@2
.3.1)
├── cardinal@0.4.4 (ansicolors@0.2.1, redeyed@0.4.4)
├── mout@0.11.0
├── bower-config@0.6.1 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1, mout@0.9
.1)
├── configstore@0.3.2 (object-assign@2.1.1, xdg-basedir@1.0.1, uuid@2.0.1, osenv
@0.1.3, js-yaml@3.3.1)
├── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
└── inquirer@0.8.0 (figures@1.3.5, ansi-regex@1.1.1, mute-stream@0.0.4, through@
2.3.8, readline2@0.1.1, chalk@0.5.1, lodash@2.4.2, cli-color@0.3.3, rx@2.5.3)
C:\Windows\system32>bower --version
1.4.1

After this
$ git clone git://github.com/byte-foundry/prototypo.git && cd prototypo
$ npm install

-----------(only) Errors & Warrnings ------------
 ~/prototypo (master)
$ npm install 
npm WARN package.json prototypo@0.1.0 license should be a valid SPDX license exp
ression
/
gyp ERR! configure error
gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not support
ed by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & <
 3.0.0.
gyp ERR! stack     at failPythonVersion (c:\Program Files\nodejs\node_modules\np
m\node_modules\node-gyp\lib\configure.js:119:14)
gyp ERR! stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:108:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:742:7)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at maybeClose (child_process.js:1015:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:1183:11)
gyp ERR! stack     at Socket.emit (events.js:107:17)
gyp ERR! stack     at Pipe.close (net.js:485:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\000\prototypo\node_modules\nexus-flux-socket.io\node_m
odules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-valid
ate
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok

gyp ERR! configure error
gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not support
ed by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & <
 3.0.0.
gyp ERR! stack     at failPythonVersion (c:\Program Files\nodejs\node_modules\np
m\node_modules\node-gyp\lib\configure.js:119:14)
gyp ERR! stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:108:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:742:7)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at maybeClose (child_process.js:1015:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:1183:11)
gyp ERR! stack     at Socket.emit (events.js:107:17)
gyp ERR! stack     at Pipe.close (net.js:485:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\000\prototypo\node_modules\nexus-flux-socket.io\node_m
odules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0

gyp ERR! configure error
gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not support
ed by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & <
 3.0.0.
gyp ERR! stack     at failPythonVersion (c:\Program Files\nodejs\node_modules\np
m\node_modules\node-gyp\lib\configure.js:119:14)
gyp ERR! stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:108:9
ERR! stack     at ChildProcess.exithandler (child_process.js:742:7)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at maybeClose (child_process.js:1015:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:1183:11)
gyp ERR! stack     at Socket.emit (events.js:107:17)
gyp ERR! stack     at Pipe.close (net.js:485:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\000\prototypo\node_modules\nexus-flux-socket.io\node_m
odules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modul
es\bufferutil
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.1.0

gyp ERR! configure error
gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not support
ed by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & <
 3.0.0.
gyp ERR! stack     at failPythonVersion (c:\Program Files\nodejs\node_modules\np
m\node_modules\node-gyp\lib\configure.js:119:14)
gyp ERR! stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:108:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:742:7)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at maybeClose (child_process.js:1015:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:1183:11)
gyp ERR! stack     at Socket.emit (events.js:107:17)
gyp ERR! stack     at Pipe.close (net.js:485:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\000\prototypo\node_modules\nexus-flux-socket.io\node_m
odules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modul
es\utf-8-validate
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.1.0
npm WARN optional dep failed, continuing utf-8-validate@1.1.0

 ~/prototypo (master)
$

Welcome to Git (version 1.9.5-preview20150319)
$ grunt serve
A valid Gruntfile could not be found. Please see the getting started guide for
more information on how to configure grunt: http://gruntjs.com/getting-started
Fatal error: Unable to find Gruntfile.

________________

Where can I get file Gruntfile.js? And Why so errors?

I also tried to install on a Mac 10.8.2 (VMware) terminal is not responding on this action "npm install" (~1 hour, then I turn it off)... and on Ubuntu installing also failed ...

What i do wrong?
Please help me :)

**Comment by FranzPoize** [comment]
Hi,

The new master branch does not run with grunt anymore. I updated the documentation to reflect that. You willl now need gulp to run prototypo. Please check the changes that have been made in the readme.md regarding running prototypo.

As for your error `gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not support
ed by gyp.` this an error with your system not with prototypo.

**Comment by asffds2014** [comment]
Unfortunately, this also couldn't help me to run your program. It's too difficult for me. I'm not a programmer I'm a designer...

**Comment by FranzPoize** [comment]
We're launching a beta version shortly for the people who supported our kickstarter campaign. And a public release is planned for this fall. You can stay tuned for the latest news by subscribing to our newsletter here http://www.prototypo.io/

**Comment by asffds2014** [comment]
Ok! Thank you Franz! +1:
