### ISSUE TITLE
Signing in is impossible

### ISSUE THREAD

**Issue by louisremi** [byte-foundry/prototypo#187]
Ok, this is embarrassing. When trying to sign-in, I get the following error

> Uncaught ReferenceError: fontInstance is not defined
Coming from https://github.com/byte-foundry/prototypo/blob/master/app/scripts/components/prototypo-canvas.components.jsx#L134

I get this problem both locally and on newui.prototypo.io, which blocks the update we intended to do this week : /

I can work around the problem by just reloading my browser. I'm already logged-in, the login screen doesn't appear, and neither does the error.

EDIT: another way to work around the problem is to click twice on the login button

**Comment by FranzPoize** [comment]
solved with 7182fb312786d93b2d4ed74997add028e497a466
