### ISSUE TITLE
When the glyphlist is open, the +/- controls are hidden

### ISSUE THREAD

**Issue by louisremi** [byte-foundry/prototypo#222]
Possible solutions : move the glyph-list to the left side, or move those controls to the left side, or find a better solution.

**Comment by kevinvennitti** [comment]
Add a class to <body> (.glyphPanelOpen e.g.) which moves these controls in CSS?

`.controls {right:10px}
.glyphPanelOpen .controls {right:210px}`

Or in Javascript.
