### ISSUE TITLE
Using keyboard to modify sliders values is effed'up

### ISSUE THREAD

**Issue by louisremi** [byte-foundry/prototypo#233]
Just try to modify the X height value using the number input and see for yourself the glyph view go wild.

**Comment by kevinvennitti** [comment]
Is it the same bug? When you change the input value with the arrows

![23-10-2015 13 40 14 - prototypo - new ui - google chrome - dev prototypo io](https://cloud.githubusercontent.com/assets/9624530/10691713/a1accd20-798b-11e5-8948-ba261664a9fa.png)

![23-10-2015 13 40 19 - using keyboard to modify sliders values is effed up issue 233 byte-foundry-prototypo - google chrome - github com](https://cloud.githubusercontent.com/assets/9624530/10691712/a1aa009a-798b-11e5-859b-fef16bfed97b.png)
