### ISSUE TITLE
Adobe stole your "concept/idea/app"

### ISSUE THREAD

**Issue by aolko** [byte-foundry/prototypo#235]
subj
https://youtu.be/bcUo9ULvVq4

**Comment by davelab6** [comment]
No curves Demo'd ;)

**Comment by kennethormandy** [comment]
Adobe actually announced they have no intentions of supporting the letter “Y” so I think you will be okay

<img width="415" alt="screenshot 2015-10-08 22 29 07" src="https://cloud.githubusercontent.com/assets/1581276/10386422/06200fb4-6e0c-11e5-9e66-12d6aefe978d.png">

**Comment by louisremi** [comment]
Haha, good catch. We're looking forward to the first beta anyway

**Comment by louisremi** [comment]
I'm marking as closed, we can continue the discussion here or via email.
