### ISSUE TITLE
A user reported that he cannot scroll in the font library

### ISSUE THREAD

**Issue by louisremi** [byte-foundry/prototypo#236]
He's @tristan_gevaux on Slack and he contacted me personnaly.

I was able to scroll in Firefox, but noted that the scrollbar is hidden under the Family blocks.

**Comment by kevinvennitti** [comment]
Same issue on Chrome / Mac El Capitan, solved with :

.fonts-collection { /* ... */ overflow:auto }

With an extra-padding at bottom.
