### ISSUE TITLE
Unable to Setup The project

### ISSUE THREAD

**Issue by anandvijay619** [byte-foundry/prototypo#243]
CHrome : 
Uncaught ReferenceError: regeneratorRuntime is not defined

**Comment by FranzPoize** [comment]
Hi ! What's your OS ?

**Comment by anandvijay619** [comment]
MAC OSX
10.10.3

Chrome Version : 46.0.2490.71

**Comment by anandvijay619** [comment]
I was able to proceed after restarting and running using sudo

**Comment by anandvijay619** [comment]
I was able to proceed after restarting and running using sudo
