### ISSUE TITLE
Inform users that the automatic saving will not perform when they are offline

### ISSUE THREAD

**Issue by yannickmathey** [byte-foundry/prototypo#285]

**Comment by FranzPoize** [comment]
- [ ] Design an offline warning or toast

- [ ] Integrate offline warning or toast

**Comment by FranzPoize** [comment]
The first step should at least be to set a value inside prototypoStore when a hoodie save return something else than an ok or a conflict.

**Comment by YoruNoHikage** [comment]
See PR
