### ISSUE TITLE
gulp can be run through npm, rather than needing separate installation

### ISSUE THREAD

**Issue by Pomax** [byte-foundry/prototypo#293]
As npm scripts run with the entire `node_modules` tree as part of its environment, the gulp task can be turned into an npm "start" script:
```
  ...
  "scripts": {
    ...
    "start": "gulp serve"
    ...
  },
  ...
  dependencies: {
    ...
    "gulp-cli": "...",
   ...
  }
  ...
```
And now people only need `node` and `git` installed, since NPM will manage gulp locally.

**Comment by passcod** [comment]
No need for `gulp-cli` in the dependencies, even, just `gulp` in the devDependencies. Gulp-cli is meant to be a global package, all it does is find the `gulp` executable in the nearest `node_modules/.bin` folder (or the global one if it doesn't find one) and run *that*, so you should never actually put it in a package.json.

**Comment by FranzPoize** [comment]
It seems it was already possible to do that. Gulp was already in the devDep and their was a npm start script that did gulp serve.
