### ISSUE TITLE
/t is far too tall in Grotesk

### ISSUE THREAD

**Issue by bensyverson** [byte-foundry/prototypo#296]
The /t is objectively too tall in the Grotesk template:

![screenshot 2016-03-29 10 06 32](https://cloud.githubusercontent.com/assets/2905922/14112866/10183548-f596-11e5-931a-9f115d842019.png)

**Comment by FranzPoize** [comment]
Hi Ben,

I think this is part of the Grotesk font t is affected by ascender the same way other glyphs with ascender are.

You can remedy to this with individualized parameters :
* Set the glyph to lowercase t using the glyph list or direct access in glyph view (click on the letter next to glyph list in the lower left of the glyph view and just press 't')
* Click on individualize parameters in the Edit menu
* Give a name to your group and click create (check that there is indeed the 't' and only the 't' in glyph selected)
* Once that is done all the param should appear yellow
* You can then modify param only for the letter 't' in your case you can lower the ascender param only for the letter 't'
* To quit the individualize parameters mode you can go to the edit menu and click on individualize parameters again or click on the button in the lower right which sould be yellow and say 'Back'

@yannickmathey is not finished with Grotesk and we will be reviewing it in the coming weeks and he'll definitely look at your issue

Thanks for your feedback :smile:

**Comment by bensyverson** [comment]
@FranzPoize Thanks for the quick reply! I understand what's happening, but it's not correct. The /t is not related to the ascenders such as /h. It's more closely related to the /i. Can you imagine if the idot went up as high as the top of the /h? So you should definitely be able to raise the /t up on an individual level, but it shouldn't grow along with the /h and other ascenders.

**Comment by yannickmathey** [comment]
will be fixed with https://github.com/byte-foundry/venus.ptf/commit/559bbb9e540063b64baee28072031d98dcc30def

thank you @bensyverson !
