### ISSUE TITLE
npm@3 doesn't nest dependencies, so webpack build fails

### ISSUE THREAD

**Issue by passcod** [byte-foundry/prototypo#302]
```
ERROR in ./app/scripts/main.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../node_modules/react-gemini-scrollbar/node_modules/gemini-scrollbar/gemini-scrollbar.css in /home/code/js/prototypo/app/scripts
 @ ./app/scripts/main.js 13:0-103
```

With [npm@3 behaviour](https://docs.npmjs.com/how-npm-works/npm3), the right place to look is now `../../node_modules/gemini-scrollbar/gemini-scrollbar.css`!

Maybe add a note in the readme that this should be used with npm@2 until the fix is actually found/made?

**Comment by passcod** [comment]
Which, for npm@3 users, can be achieved locally (for Prototypo only) by:

```
~/prototypo> rm -r node_modules # If you've already tried to npm install
~/prototypo> npm install npm@2
~/prototypo> node_modules/.bin/npm install
```

That will also work for people with npm@2 installed globally, but there's not much point, then.

**Comment by Xavours** [comment]
Hi,
I tried to install prototypo, had the same problem and tried your solution. It does not seem to work as i get that error :
```
WARNING in ./~/moment/min/moment-with-locales.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./locale in /Users/xavier/Documents/prototypo/node_modules/moment/min
 @ ./~/moment/min/moment-with-locales.js 346:16-43
webpack: bundle is now VALID.
```

Any thought ?
Thx !

**Comment by passcod** [comment]
Yeah, I get that warning too, but Prototypo works fine.
