### ISSUE TITLE
Tutorial issue

### ISSUE THREAD

**Issue by yannPrototypo** [byte-foundry/prototypo#312]
<img width="288" alt="bug tuto" src="https://cloud.githubusercontent.com/assets/17646529/16687388/a1ee27a8-4518-11e6-8021-6afd5245365a.png">

**Comment by yannPrototypo** [comment]
![image](https://cloud.githubusercontent.com/assets/17646529/16687430/e23708ca-4518-11e6-8963-e2ae2c6f3dec.png)

**Comment by yannickmathey** [comment]
There is no visible button to close or exit the tutorial

**Comment by FranzPoize** [comment]
no more tutos
