### ISSUE TITLE
Explain the use of px and % with a tool tip

### ISSUE THREAD

**Issue by yannPrototypo** [byte-foundry/prototypo#324]
![image](https://cloud.githubusercontent.com/assets/17646529/17017095/39a686e4-4f32-11e6-999e-e24bd28fd185.png)

**Comment by louisremi** [comment]
I would even replace "%" with "×" and "px" with "+", as those "units" may feel familiar to web designers, but they aren't a good illustration of what is going on.
For example:
- in "%" mode, the value is generally between 0 and 2. So this is a coefficient, not a percentage
- some sliders have values that aren't expressed in pixels. What does the "px" mode mean for slant?

For the tooltip text, I suggest:
- "the value of this slider will multiply the global value"
- "the value of this slider will be added to the global value"

Also, I suggest renaming the "individualization groups" feature to the "adjustment groups" feature.
