### ISSUE TITLE
When glyph view is hidden we can't close glyph list

### ISSUE THREAD

**Issue by yannickmathey** [byte-foundry/prototypo#334]
![capture d ecran 2016-07-27 a 19 22 51](https://cloud.githubusercontent.com/assets/859119/17185037/a6759772-542f-11e6-995e-9fa2a26de136.png)

Should we add a close button?

**Comment by FranzPoize** [comment]
yep where?

**Comment by FranzPoize** [comment]
This is refactoring of the UX of the glyph list issue:

- Is the glyph list suppose to be shown when the glyph view isn't there?
- Should the glyph list have other uses than just show the glyph in the glyph view?

**Comment by yannickmathey** [comment]
Since we can add special characters thanks to the new word input, the glyph list haven't other uses when he glyph view is hidden

**Comment by yannickmathey** [comment]
The close button hide both glyph view and list but not the views button (the toggle)
