### ISSUE TITLE
After windows reload, some letters are not build

### ISSUE THREAD

**Issue by yannickmathey** [byte-foundry/prototypo#348]
Letters made from components? /Aacute + /adieresis

![capture d ecran 2016-08-04 a 14 14 26](https://cloud.githubusercontent.com/assets/859119/17401435/f6ececa4-5a4d-11e6-891e-e8601b6c12ff.png)

no errors in the console

**Comment by FranzPoize** [comment]
@yannickmathey tu peux pull et test ?
