### ISSUE TITLE
Visual bug on "my account > account settings"

### ISSUE THREAD

**Issue by MartinBolot** [byte-foundry/prototypo#353]
To much space below the first "display-with-label" element, might be link to flex:1 css property

url is https://dev.prototypo.io/#/account/details
![capture d ecran 2016-08-04 a 17 20 16](https://cloud.githubusercontent.com/assets/5830219/17407536/eea74b38-5a67-11e6-8a73-eaf5b4c6e410.png)

**Comment by yannickmathey** [comment]
Pic or didn't happen
