### ISSUE TITLE
Strange bug in "My billing adress" part of "my account"

### ISSUE THREAD

**Issue by MartinBolot** [byte-foundry/prototypo#356]
I get "Uncaught TypeError: Cannot read property 'getBuyerName' of undefined" if I click on the button

![capture d ecran 2016-08-04 a 17 50 27](https://cloud.githubusercontent.com/assets/5830219/17408638/525d7b6c-5a6c-11e6-8c04-8aca80c367ea.png)

**Comment by FranzPoize** [comment]
what's the account?
