### ISSUE TITLE
Reset all parameters + manual changes

### ISSUE THREAD

**Issue by yannickmathey** [byte-foundry/prototypo#474]
The reset does not reset manual modifications

**Comment by yannickmathey** [comment]
maybe @Aldrian can fix this issue with his last commits?

**Comment by Aldrian** [comment]
You mean that clicking the edit > reset all parameters will also reset all manual modifications? Should I also update the label?

**Comment by Aldrian** [comment]
Fixed with e916c8bd55e571d798857e0d7dbf193f78311df9
