### ISSUE TITLE
Contour points are not displayed when we don't click on skeleton node

### ISSUE THREAD

**Issue by yannickmathey** [byte-foundry/prototypo#499]
[manual editing mode]

click on the extremity of a node segment (where a contour node should be present): you will be able to modify the width, etc. but the contour points are not displayed (but remain on the node we clicked previously)

![capture d ecran 2016-12-01 a 17 50 13](https://cloud.githubusercontent.com/assets/859119/20803194/a412b744-b7ee-11e6-9fda-8234fb16dbb5.png)

**Comment by FranzPoize** [comment]
Should be resolved with byte-foundry/prototypo-canvas@1.16.0
