### ISSUE TITLE
Glyph reset does not work when we use alternates

### ISSUE THREAD

**Issue by yannickmathey** [byte-foundry/prototypo#502]
- Switch to grotesk template
- Set the canvas with the a (single story)
- change a node position

the button reset is still inactive

![capture d ecran 2016-12-04 a 19 31 12](https://cloud.githubusercontent.com/assets/859119/20868284/3e5114e8-ba58-11e6-9ad1-c1aac1b87a76.png)

**Comment by Aldrian** [comment]
Fixed with #503
