### ISSUE TITLE
Add fallback for when user signin and they apparently don't have a stripe user

### ISSUE THREAD

**Issue by FranzPoize** [byte-foundry/prototypo#554]
When during sign up the stripe fetch doesn't work user don't have a stripe account and cannot login subsequently.

- [ ] Add a fallback during login if we don't find a stripe account for the user

- [ ] Tell the user that they can't login due to an error in network if we can't create that stripe account

- [ ] Give them access to intercom and send automatic message to let them know that we can help

**Comment by YoruNoHikage** [comment]
This has been fix, the stripe is created on the backend side.
