### ISSUE TITLE
Word view drag line is not set on loading

### ISSUE THREAD

**Issue by yannickmathey** [byte-foundry/prototypo#570]
The word view height is fine, but the drag line is always on the top when you load the app. You can still drag this one to change the height though

![screenshot](https://cloud.githubusercontent.com/assets/859119/25037817/8c82d408-20fb-11e7-80b9-2d9016679ff2.jpeg)

![word-view](https://cloud.githubusercontent.com/assets/859119/25037786/55415492-20fb-11e7-8470-7a5cd520cf6d.gif)

**Comment by Aldrian** [comment]
Fixed in 7a3d181a945808dde6081d723fef7a443c50746f.
