### ISSUE TITLE
Missing ui in manual editing mode

### ISSUE THREAD

**Issue by nbesset** [byte-foundry/prototypo#597]
I used the Elzevir template for working on the letter "o" when something happened I couldn't change the rotation of the node contour and his thickness. 

  
![capture d ecran 2017-07-13 a 16 48 06](https://user-images.githubusercontent.com/30152385/28172215-41c1393c-67eb-11e7-99e1-c9b79c575612.png)

**Comment by YoruNoHikage** [comment]
It should be fixed with byte-foundry/elzevir.ptf#9
