### ISSUE TITLE
Merged template

### ISSUE THREAD

**Issue by nbesset** [byte-foundry/prototypo#599]
I give this name to a project "Preset 1" I delete it after to remake another template with the same name both of them merge. Let me introduce you the grotospectro 
![capture d ecran 2017-07-18 a 17 07 02](https://user-images.githubusercontent.com/30152385/28324447-b5e52b7c-6bdb-11e7-95fc-37344be788cd.png)

**Comment by yannickmathey** [comment]
Not so bad, though.

**Comment by YoruNoHikage** [comment]
Fixed when we moved to Graphcool
