### ISSUE TITLE
Paragraph View

### ISSUE THREAD

**Issue by davelab6** [byte-foundry/prototypo#64]
Instead of "Switch" being a toggle between a char and word level view, it should be 3 buttons similar to the 3 buttons you use to change vertical/horizontol/serif slider sets, that go from char to word to paragraph. 

www.google.com/fonts has similar tabs for this, and http://littleipsum.com has a nice widget for selecting text amounts that could also be used:

![screenshots_menu_bar](https://f.cloud.github.com/assets/261579/2055432/ae050e50-8ac4-11e3-82fc-e8f39925afad.png)

I don't like the duplication of the views across the left col and main area; I'd prefer to see more sliders on screen and have all the previews in the main area; having the main area split into 3 rows, to see para/word/char at the same time, would be better.

**Comment by louisremi** [comment]
Fixed in recent versions
