### ISSUE TITLE
Help!?

### ISSUE THREAD

**Issue by Fiddy187** [byte-foundry/prototypo#667]
I have posted here previous about trying to get this to run and it got deleted for some reason...

I have been trying to get this to work for a few MONTHS now and I can't figure it out.  I have github desktop app installed, node JS with NPM, Git, and everything else.

Can we get some decent instructions on how to actually install/run this? Is there a video? Anything?????

**Comment by yannickmathey** [comment]
Hello, we don't usually delete issues. I don't know how Github Desktop works, but I guess it can skip some important steps during the installation.

The procedure is quite simple:

- Git clone prototypo
- Be sure to Git checkout the Master branch
- Yarn install in the prototypo folder (global install Yarn before)
- Yarn Start to launch the app

If it doesn't work, can we get some decent informations on the error you are experiencing? Thank you.

**Comment by Aldrian** [comment]
We're still here if you need help running the app locally.
Closing this for more visibility on the current issues.

Oh, and I don't see any record of your previous issue, see for yourself:

![image](https://user-images.githubusercontent.com/5655615/43009387-d0f8c4f4-8c3d-11e8-8d8b-5ee7fa2fb534.png)


Have a nice day!
