### ISSUE TITLE
Librairie base: export famille

### ISSUE THREAD

**Issue by FranzPoize** [byte-foundry/prototypo#682]
## Description

Allow users to download a whole family. All the variants should be package in a zip file. Their fontinfo should be set according to the values set in the family settings screen

![image](https://user-images.githubusercontent.com/971751/42882757-dc83a78a-8a99-11e8-987a-90b4eb1d6d8c.png)

This options should be available from the font list, the side bar in the variant list and in the sidebar in the family settings.

## Planning info
Estimated time spent 1,5
By @Aldrian 
Sprint 27-28 from 13/07/2018

**Comment by Aldrian** [comment]
Done in c3a8b6c9a41ba9ca999b2341db6eef53e2c9f7c7 a2892e7ffbafba8ca1dc658214a80716a9cecd12 0aef4cecfdc84e5eb3fe68431e5d331bb3d661d1
Time spent 1.5.
