### ISSUE TITLE
Librairie base: ecran mes fonts

### ISSUE THREAD

**Issue by FranzPoize** [byte-foundry/prototypo#683]
## Description
A screen that only shows the font created by the users. It should be accessible from the left sidebar under the All button.
![image](https://user-images.githubusercontent.com/971751/42883018-ac0bb696-8a9a-11e8-832c-de1c4c1df3e9.png)

This is just a filter of the all list that just displays the font that have been create by the users.

## Planning Info
Time estimated 0,5
By @Aldrian 
Sprint 27-29 from 13/07/2018

**Comment by Aldrian** [comment]
Done in a50fa013a9235d99f9de876df8635294bfa47ae4
Spent 1.
This took more that estimated because of the previous filter. I had to rework the system to avoid side-effects and deal with more filters later.
