### ISSUE TITLE
Librairie team: liste

### ISSUE THREAD

**Issue by FranzPoize** [byte-foundry/prototypo#684]
## Description
The team list is a list of font created by the users that share a manager. It is accessed by a button in the sidebar. Once the button is selected a sample of the families available is displayed under it like so:
![image](https://user-images.githubusercontent.com/971751/42883317-8b323c28-8a9b-11e8-8d81-11adf40c36bc.png)
If there is more than 10 fonts available in the team library, the first 10 fonts name should be displayed and an eleventh item should be displayed with text "and x more"
![image](https://user-images.githubusercontent.com/971751/42883465-f3e5e990-8a9b-11e8-895c-1546b0188d9d.png)

The team list is just like the all list with one difference
![image](https://user-images.githubusercontent.com/971751/42883678-8e7b1f70-8a9c-11e8-9555-0a8bf25f13c1.png)
1. There is no edit button for the moment.
For the moment the variant list of a team font is the same as the variant list of a user font except the variant are not editable
![image](https://user-images.githubusercontent.com/971751/42883804-eb3c4c34-8a9c-11e8-8aca-e855ce810848.png)

## Planning Info
Time estimated 3
By @Aldrian 
Sprint 27-29 from 13/07/2018

**Comment by Aldrian** [comment]
Done in 5e7a84ad37b688f09b323bd89fccc5e6756e5711

Also added the family list for personnal projects on the sidebars
And the variant infos on the family view.

![image](https://user-images.githubusercontent.com/5655615/43008198-b2ccd7ca-8c3a-11e8-8455-6a37bbf8c3e8.png)
![image](https://user-images.githubusercontent.com/5655615/43008232-c554c3bc-8c3a-11e8-98b0-1a33915d4d82.png)

Spent 1.5.
