### ISSUE TITLE
Librairie team: fonts in use

### ISSUE THREAD

**Issue by FranzPoize** [byte-foundry/prototypo#686]
## Description
Not only for teams, but for all users
What needs to be done:

* Update the model to add a fontinuse type
* Add an "add fontinuse" button to the right sidebar when viewing a project
* Create a screen with a form to fill up all the fontinuse data (designer + url, client + url, images, fonts to link)
* Add a "fontinuse" tab on the left sidebar and a fontinuse recap screen similar to library-list
## Planning info
Time estimated for spec 0,5
Time estimated 3
By @Aldrian 
Sprint 27-28 from 13/07/2018

**Comment by Aldrian** [comment]
Not only for teams, but for all users
What needs to be done: 
- Update the model to add a fontinuse type
- Add an "add fontinuse" button to the right sidebar when viewing a project
- Create a screen with a form to fill up all the fontinuse data (designer + url, client + url, images, fonts to link)
- Add a "fontinuse" tab on the left sidebar and a fontinuse recap screen similar to library-list
Estimated 3

**Comment by Aldrian** [comment]
Done in 7eaf9de978bf8bf1e40897fc027e72e3234884df
Spent 4 because I had to abstract the font system and work on the favourites on the same time.
