### ISSUE TITLE
Librairie hosting: there is nothing here

### ISSUE THREAD

**Issue by FranzPoize** [byte-foundry/prototypo#687]
## Description
This is the screen that is showed to a user that is not hosting any font for the moment
![image](https://user-images.githubusercontent.com/971751/42888961-9ed94146-8aa9-11e8-96d1-8efa36339786.png)
## Additional info
This is an UI task. Only the UI should be done and the backend and update logic will be added later.
## Planning info
Time estimated for spec 0,5
By @Aldrian 
Sprint 27-28 from 13/07/2018

**Comment by Aldrian** [comment]
91fd37f7ac1b72c8acdb7d0d4befe5f1e9bf5da6
0.5 with analysing the existing hosting system
