### ISSUE TITLE
Librairie hosting: ecran liste

### ISSUE THREAD

**Issue by FranzPoize** [byte-foundry/prototypo#688]
## Description
This is the screen where the list of the domains name is displayed It should look like this
![image](https://user-images.githubusercontent.com/971751/42889139-ff60b9a4-8aa9-11e8-89c5-68d4e20aee28.png)
## Additional info
This is an UI task. Only the UI should be done and the backend and update logic will be added later.
## Planning info
Time estimated 1.5
By @Aldrian 
Sprint 27-28 from 13/07/2018

**Comment by Aldrian** [comment]
297581d6d64e40af943a98a4e587bb26ce99d5cb
Spent 0.5.
