### ISSUE TITLE
Librairie hosting: ecran add a new website

### ISSUE THREAD

**Issue by FranzPoize** [byte-foundry/prototypo#689]
## Description
This is the screen where a user can add a new domain name. It is composed of an input where the user should enter the domain name. It should validate that domain name to ensure it is of the proper format (
(www.)?domainame.com )
![image](https://user-images.githubusercontent.com/971751/42889711-5e45a0a0-8aab-11e8-9cc7-675a5923e86a.png)
* The list of font contains the font that have been added to this domain name.
* Each font is displayed with the font generated from the values of their family and variant.
* When the font is clicked a menu is displayed with the button remove and update.
* If two font have the same family name and weight a message should be displayed on the second warning the user that this will not work.
* Below the fonts there is a search bar with an add button
* A submit button at the bottom of the page

## Additional info
This is an UI task. Only the UI should be done and the backend and update logic will be added later.

## Planning info
Time estimated 2
By @Aldrian 
Sprint 27-28 from 13/07/2018

**Comment by Aldrian** [comment]
Done in 7b9aa84a2c3fbfcfc61194881354c78e203a80cb
Time spent 2
