### ISSUE TITLE
Librairie hosting: search autocomplete

### ISSUE THREAD

**Issue by FranzPoize** [byte-foundry/prototypo#690]
## Description
The search input of the hosting add website screen. This is what it should look like when searching (I am not a designer)
![image](https://user-images.githubusercontent.com/971751/42895692-eda38884-8aba-11e8-81f3-edbc8c4c8349.png)
* The search should just make a contains filter for the moment
* User should be able to scroll through the results
## Planning info
Time estimated 2
By @Aldrian 
Sprint 28-29 from 27/07/2018

**Comment by Aldrian** [comment]
Done in 7b9aa84a2c3fbfcfc61194881354c78e203a80cb for #689 (amongst other things) (sorry)

Time spent: 0 (I guess?)
