### ISSUE TITLE
Apollo: account

### ISSUE THREAD

**Issue by FranzPoize** [byte-foundry/prototypo#694]
## Description
composants: 3
mettre à jour les composants qui dépendent de la source Stripe

## Planning info
Time estimated 2
By @YoruNoHikage 
Sprint 27-28 from 13/07/2018

**Comment by YoruNoHikage** [comment]
Done in #711 
A lot has been done in the mix, which makes it difficult to measure it.

From now on measuring the tasks time should be easier.
