### ISSUE TITLE
Prevent strokes from becoming imbalanced

### ISSUE THREAD

**Issue by davelab6** [byte-foundry/prototypo#70]
In any font editor, it is easy to make 2 sibling outline contours lose their coherence, their ability to give the illusion of a single stroke from 2 actually-unrelated lines. This is true of Prototypo too. 

Here is an example, where the top left of the 'e' loses it stroke illusion:

![screen shot 2014-02-01 at 12 11 27](https://f.cloud.github.com/assets/261579/2061815/f7bd1eb8-8c6b-11e3-8936-6f0d133337b8.png)

It would be good for Prototypo to prevent this.

**Comment by louisremi** [comment]
Solved as we've switched to skeleton based outlines. Any remaining problems should be listed in different issues.
