### ISSUE TITLE
[Serif Curve] shouldn’t elongate serifs

### ISSUE THREAD

**Issue by loicsander** [byte-foundry/prototypo#85]
Presently, the way to handle serif modification in using [Serif Width] and [Serif Curve] isn’t quite straightforward (although operational).

[Serif Width] pushes the extreme points away from the first point of the serif curve, and if you use the [Serif Curve] slider it broadens the curve and also makes the serif wider, which isn’t really expected.

So [Serif Curve] shouldn’t widen serifs and should use the actual width of the serif as a upper limit.

**Comment by yannickmathey** [comment]
New build of serifs in John-Fell
![curveserif](https://cloud.githubusercontent.com/assets/859119/7070922/5f8f3ae8-dee2-11e4-8584-4c22c32eccb8.png)
