### ISSUE TITLE
Make the app installable.

### ISSUE THREAD

**Issue by louisremi** [byte-foundry/prototypo#93]
Several manifest should be generated to make the app installable on various platforms:
- Chrome: http://developer.chrome.com/apps/first_app.html
- Firefox: https://developer.mozilla.org/en-US/Apps/Developing/installable_apps
- Safari iOS: https://developer.apple.com/library/mac/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html
- IE: http://msdn.microsoft.com/en-US/library/ie/bg183312%28v=vs.85%29

**Comment by Aldrian** [comment]
Should we close this one considering that we have the native apps?
